cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_12/perturbation/SymmetryFactor 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_12 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_12/perturbation/Energy 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_12 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_12/perturbation/ImaginaryFrequency 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_12 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_12/perturbation/Frequencies 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_12 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_12/perturbation/PowerOne 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_12 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_12/perturbation/FactorOne 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_12 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_12/perturbation/HinderRotor 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
