python MESS_rate_extractor.py tripplet_B8_SymmetryFactor_1_0.1.out 0.1\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B8_SymmetryFactor_1_0.1.out 0.5\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B8_SymmetryFactor_1_0.1.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B8_SymmetryFactor_1_0.1.out 2.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B8_SymmetryFactor_1_0.1.out 4.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_W1b_SymmetryFactor_1_0.1.out 0.1\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_W1b_SymmetryFactor_1_0.1.out 0.5\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_W1b_SymmetryFactor_1_0.1.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_W1b_SymmetryFactor_1_0.1.out 2.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_W1b_SymmetryFactor_1_0.1.out 4.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_W1a_SymmetryFactor_1_0.1.out 0.1\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_W1a_SymmetryFactor_1_0.1.out 0.5\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_W1a_SymmetryFactor_1_0.1.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_W1a_SymmetryFactor_1_0.1.out 2.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_W1a_SymmetryFactor_1_0.1.out 4.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B1_SymmetryFactor_1_0.1.out 0.1\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B1_SymmetryFactor_1_0.1.out 0.5\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B1_SymmetryFactor_1_0.1.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B1_SymmetryFactor_1_0.1.out 2.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B1_SymmetryFactor_1_0.1.out 4.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
