python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 0.1\ atm P1 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 1.0\ atm P1 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 4\ atm P1 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 0.1\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 4\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 0.1\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 1.0\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 4\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 0.1\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 1.0\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 4\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 0.1\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 1.0\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 4\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 0.1\ atm P2 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 1.0\ atm P2 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 4\ atm P2 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 0.1\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 1.0\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 4\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 0.1\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 1.0\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 4\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 0.1\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 1.0\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 4\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 0.1\ atm P3 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 1.0\ atm P3 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 4\ atm P3 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 0.1\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 1.0\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 4\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 0.1\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 1.0\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 4\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 0.1\ atm P4 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 1.0\ atm P4 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 4\ atm P4 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 0.1\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 1.0\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 4\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 0.1\ atm P5 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 1.0\ atm P5 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
python MESS_rate_extractor.py combined_W1b_Energy_1_0.0.out 4\ atm P5 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_21/nominal False 
