python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm R W1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm R W1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm R W1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm R W1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm R W1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm R P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm R P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm R P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm R P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm R P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm R P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm R P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm R P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm R P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm R P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm R P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm R P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm R P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm R P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm R P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm R P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm R P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm R P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm R P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm R P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm R P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm R P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm R P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm R P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm R P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm R P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm R P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm R P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm R P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm R P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm P1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm P1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm P1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm P1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm P1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm P2 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm P2 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm P2 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm P2 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm P2 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm P3 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm P3 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm P3 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm P3 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm P3 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm P4 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm P4 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm P4 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm P4 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm P4 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.001\ atm P5 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.01\ atm P5 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 0.1\ atm P5 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 1.0\ atm P5 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
python MESS_rate_extractor.py ch3oh_W1_Energy_1_0.0.out 10.0\ atm P5 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_11/nominal False 
