cd /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_34/perturbation/Epsilons 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_34 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_34/perturbation/PowerOne 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_34 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_34/perturbation/FactorOne 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_34 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_34/perturbation/Energy 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_34 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_34/perturbation/Sigmas 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
