python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.1\ atm P1 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.5\ atm P1 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 1.0\ atm P1 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 2.0\ atm P1 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 4.0\ atm P1 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.1\ atm W3 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.5\ atm W3 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 1.0\ atm W3 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 2.0\ atm W3 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 4.0\ atm W3 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.1\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.5\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 1.0\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 2.0\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 4.0\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.1\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.5\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 1.0\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 2.0\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 4.0\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.1\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.5\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 1.0\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 2.0\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 4.0\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.1\ atm P3 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.5\ atm P3 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 1.0\ atm P3 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 2.0\ atm P3 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 4.0\ atm P3 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.1\ atm W3 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.5\ atm W3 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 1.0\ atm W3 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 2.0\ atm W3 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 4.0\ atm W3 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.1\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.5\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 1.0\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 2.0\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 4.0\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.1\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.5\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 1.0\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 2.0\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 4.0\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.1\ atm P4 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.5\ atm P4 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 1.0\ atm P4 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 2.0\ atm P4 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 4.0\ atm P4 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.1\ atm W3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.5\ atm W3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 1.0\ atm W3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 2.0\ atm W3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 4.0\ atm W3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.1\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.5\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 1.0\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 2.0\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 4.0\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.1\ atm P5 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.5\ atm P5 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 1.0\ atm P5 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 2.0\ atm P5 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 4.0\ atm P5 W3 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.1\ atm W3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 0.5\ atm W3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 1.0\ atm W3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 2.0\ atm W3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
python MESS_rate_extractor.py singlet_W3_Energy_1_0.0.out 4.0\ atm W3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_7/nominal False 
