cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_14/perturbation/SymmetryFactor 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_14 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_14/perturbation/Energy 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_14 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_14/perturbation/ImaginaryFrequency 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_14 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_14/perturbation/Frequencies 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_14 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_14/perturbation/PowerOne 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_14 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_14/perturbation/FactorOne 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_14 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/singlet/calculation_14/perturbation/HinderRotor 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
