cd /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_8/perturbation/Epsilons 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_8 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_8/perturbation/Energy 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_8 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_8/perturbation/Power 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/combined/calculation_8 
