cd /home/jl/MSI_Theory/PAPR-MESS_calculation/N2+O2/calculation_7/perturbation/SymmetryFactor 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/jl/MSI_Theory/PAPR-MESS_calculation/N2+O2/calculation_7 
cd /home/jl/MSI_Theory/PAPR-MESS_calculation/N2+O2/calculation_7/perturbation/Energy 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/jl/MSI_Theory/PAPR-MESS_calculation/N2+O2/calculation_7 
cd /home/jl/MSI_Theory/PAPR-MESS_calculation/N2+O2/calculation_7/perturbation/Frequencies 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/jl/MSI_Theory/PAPR-MESS_calculation/N2+O2/calculation_7 
cd /home/jl/MSI_Theory/PAPR-MESS_calculation/N2+O2/calculation_7/perturbation/ImaginaryFrequency 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/jl/MSI_Theory/PAPR-MESS_calculation/N2+O2/calculation_7 
