cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_13/perturbation/Energy 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_13 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_13/perturbation/Frequencies 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_13 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_13/perturbation/NejScale 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_13 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_13/perturbation/VariationalFrequencies 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_13 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_13/perturbation/ImaginaryFrequency 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_13 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_13/perturbation/HinderRotor 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_13 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_13/perturbation/VariationalEnergy 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_13 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_13/perturbation/SymmetryFactor 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_13 
