python MESS_rate_extractor.py tripplet_W1b_Energy_1_34.9759.out 0.1\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_W1b_Energy_1_34.9759.out 0.5\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_W1b_Energy_1_34.9759.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_W1b_Energy_1_34.9759.out 2.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_W1b_Energy_1_34.9759.out 4.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B8_Energy_1_34.9759.out 0.1\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B8_Energy_1_34.9759.out 0.5\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B8_Energy_1_34.9759.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B8_Energy_1_34.9759.out 2.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B8_Energy_1_34.9759.out 4.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B1_Energy_1_34.9759.out 0.1\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B1_Energy_1_34.9759.out 0.5\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B1_Energy_1_34.9759.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B1_Energy_1_34.9759.out 2.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B1_Energy_1_34.9759.out 4.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B2_Energy_1_34.9759.out 0.1\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B2_Energy_1_34.9759.out 0.5\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B2_Energy_1_34.9759.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B2_Energy_1_34.9759.out 2.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_B2_Energy_1_34.9759.out 4.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_W1a_Energy_1_34.9759.out 0.1\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_W1a_Energy_1_34.9759.out 0.5\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_W1a_Energy_1_34.9759.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_W1a_Energy_1_34.9759.out 2.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
python MESS_rate_extractor.py tripplet_W1a_Energy_1_34.9759.out 4.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation False 
