cd /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation/Frequencies 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation/Energy 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation/SymmetryFactor 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation/Epsilons 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation/PowerOne 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation/FactorOne 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation/ImaginaryFrequency 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5/perturbation/Sigmas 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/tripplet/calculation_5 
