cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_16/perturbation/Energy 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_16 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_16/perturbation/Frequencies 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_16 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_16/perturbation/NejScale 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_16 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_16/perturbation/VariationalFrequencies 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_16 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_16/perturbation/ImaginaryFrequency 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_16 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_16/perturbation/HinderRotor 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_16 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_16/perturbation/VariationalEnergy 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_16 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_16/perturbation/SymmetryFactor 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3oh/calculation_16 
