cd /home/mcb/MSI_Theory/PAPR-MESS_calculation/N2+O2/calculation_17/perturbation/SymmetryFactor 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/mcb/MSI_Theory/PAPR-MESS_calculation/N2+O2/calculation_17 
cd /home/mcb/MSI_Theory/PAPR-MESS_calculation/N2+O2/calculation_17/perturbation/Energy 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/mcb/MSI_Theory/PAPR-MESS_calculation/N2+O2/calculation_17 
cd /home/mcb/MSI_Theory/PAPR-MESS_calculation/N2+O2/calculation_17/perturbation/Frequencies 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/mcb/MSI_Theory/PAPR-MESS_calculation/N2+O2/calculation_17 
cd /home/mcb/MSI_Theory/PAPR-MESS_calculation/N2+O2/calculation_17/perturbation/ImaginaryFrequency 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/mcb/MSI_Theory/PAPR-MESS_calculation/N2+O2/calculation_17 
